#!/usr/bin/env bash

choice=$(printf "Lock\nLogout\nReboot\nShutdown\nSuspend" | rofi -dmenu -i -p "Power")

case "$choice" in
  Lock)    loginctl lock-session ;;
  Logout)  hyprctl dispatch exit ;;
  Reboot)  systemctl reboot ;;
  Shutdown) systemctl poweroff ;;
  Suspend) systemctl suspend ;;
esac
