#!/bin/bash

# tmux new-session -d -s dotfiles -c $HOME/dotfiles
# tmux new-session -d -s books -c $HOME/angel-dx/Books
# tmux new-session -d -s byte-arena -c $HOME/angel-dx/byte-arena
# tmux new-session -d -s cp -c $HOME/angel-dx/byte-arena/cp
# tmux new-session -d -s sysinit -c $HOME/angel-dx/byte-arena/sysinit
# tmux new-session -d -s qtile -c $HOME/.config/qtile
# tmux new-session -d -s live-nvim -c $HOME/.config/nvim
# tmux new-session -d -s hypr -c $HOME/.config/hypr
# tmux new-session -d -s waybar -c $HOME/.config/waybar


tmux new-session -d -s mal -c $HOME/sinopx/mal/
tmux new-session -d -s dotfiles -c $HOME/dotfiles
tmux new-session -d -s live-nvim -c $HOME/.config/nvim
# tmux new-session -d -s www_sinopx -c $HOME/sinopx/www_sixnopx/
tmux new-session -d -s www_sinopx -c $HOME/sinopx/www_sixnopx/ \; send-keys "source .venv/bin/activate" C-m
