#!/bin/bash

# Check if user passed a command
if [ $# -eq 0 ]; then
  echo "Usage: $0 <command>"
  exit 1
fi

# tmux display-popup -w 70% -h 70% "$*"
tmux display-popup -w 70% -h 70% "$(printf "%q " "$@")"

